<script lang="ts">
	// THIS FILE WAS AUTOMATICALLY GENERATED BY generate.js IN THE ROOT DIRECTORY. DO NOT EDIT.

	import type { IconTheme, IconProps } from '$lib/types.js';

	let { theme = 'outline', class: cssClass, style: cssStyle }: IconProps = $props();

	export const NAME = `%NAME%`;

	const SVGS: Record<IconTheme, string> = {
		outline: `%OUTLINE_SVG%`,
		solid: `%SOLID_SVG%`,
		mini: `%MINI_SVG%`,
		micro: `%MICRO_SVG%`
	};

	function htmlEscape(text?: string): string {
		if (!text) {
			return '';
		}
		return text
			.replaceAll('&', '&amp;')
			.replaceAll('<', '&lt;')
			.replaceAll('>', '&gt;')
			.replaceAll('"', '&quot;')
			.replaceAll("'", '&#39;');
	}
</script>

{@html SVGS[theme] //
	.replace('%class%', htmlEscape(cssClass))
	.replace('%style%', htmlEscape(cssStyle))}
