<script lang="ts">
	// THIS FILE WAS AUTOMATICALLY GENERATED BY generate.js IN THE ROOT DIRECTORY. DO NOT EDIT.

	import type { IconTheme, IconProps } from '$lib/types.js';

	let { theme = 'outline' }: IconProps = $props();

	export const NAME = `IconSlash`;

	const SVGS: Record<IconTheme, string> = {
		outline: `<svg data-type="svelte-heroicons" data-icon="IconSlash" data-theme="outline" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M9 20.2475L15 3.74707" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`,
		solid: `<svg data-type="svelte-heroicons" data-icon="IconSlash" data-theme="solid" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M15.256 3.04243C15.6453 3.18399 15.8461 3.61434 15.7046 4.00364L9.7046 20.504C9.56304 20.8933 9.13271 21.0942 8.74342 20.9526C8.35414 20.811 8.15331 20.3807 8.29487 19.9914L14.2948 3.49099C14.4364 3.1017 14.8667 2.90087 15.256 3.04243Z" fill="currentColor"/>
</svg>
`,
		mini: `<svg data-type="svelte-heroicons" data-icon="IconSlash" data-theme="mini" aria-hidden="true" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M12.5284 3.04731C12.9177 3.18887 13.1185 3.61919 12.977 4.00846L8.43308 16.5042C8.29152 16.8935 7.8612 17.0943 7.47192 16.9527C7.08265 16.8112 6.88183 16.3809 7.02339 15.9916L11.5673 3.49585C11.7088 3.10657 12.1392 2.90576 12.5284 3.04731Z" fill="currentColor"/>
</svg>
`,
		micro: `<svg data-type="svelte-heroicons" data-icon="IconSlash" data-theme="micro" aria-hidden="true" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M10.0741 2.04731C10.4634 2.18887 10.6642 2.61919 10.5227 3.00846L6.70505 13.5069C6.56349 13.8962 6.13317 14.097 5.7439 13.9555C5.35462 13.8139 5.1538 13.3836 5.29536 12.9943L9.11299 2.49585C9.25454 2.10657 9.68486 1.90576 10.0741 2.04731Z" fill="currentColor"/>
</svg>
`
	};
</script>

{@html SVGS[theme]}
