<script lang="ts">
	// THIS FILE WAS AUTOMATICALLY GENERATED BY generate.js IN THE ROOT DIRECTORY. DO NOT EDIT.

	import type { IconTheme, IconProps } from '$lib/types.js';

	let { theme = 'outline' }: IconProps = $props();

	export const NAME = `IconStop`;

	const SVGS: Record<IconTheme, string> = {
		outline: `<svg data-type="svelte-heroicons" data-icon="IconStop" data-theme="outline" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.25 7.5C5.25 6.25736 6.25736 5.25 7.5 5.25H16.5C17.7426 5.25 18.75 6.25736 18.75 7.5V16.5C18.75 17.7426 17.7426 18.75 16.5 18.75H7.5C6.25736 18.75 5.25 17.7426 5.25 16.5V7.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`,
		solid: `<svg data-type="svelte-heroicons" data-icon="IconStop" data-theme="solid" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M4.5 7.5C4.5 5.84315 5.84315 4.5 7.5 4.5H16.5C18.1569 4.5 19.5 5.84315 19.5 7.5V16.5C19.5 18.1569 18.1569 19.5 16.5 19.5H7.5C5.84315 19.5 4.5 18.1569 4.5 16.5V7.5Z" fill="currentColor"/>
</svg>
`,
		mini: `<svg data-type="svelte-heroicons" data-icon="IconStop" data-theme="mini" aria-hidden="true" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.25 3C4.00736 3 3 4.00736 3 5.25V14.75C3 15.9926 4.00736 17 5.25 17H14.75C15.9926 17 17 15.9926 17 14.75V5.25C17 4.00736 15.9926 3 14.75 3H5.25Z" fill="currentColor"/>
</svg>
`,
		micro: `<svg data-type="svelte-heroicons" data-icon="IconStop" data-theme="micro" aria-hidden="true" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect x="3" y="3" width="10" height="10" rx="1.5" fill="currentColor"/>
</svg>
`
	};
</script>

{@html SVGS[theme]}
