<script lang="ts">
	// THIS FILE WAS AUTOMATICALLY GENERATED BY generate.js IN THE ROOT DIRECTORY. DO NOT EDIT.

	import type { IconTheme, IconProps } from '$lib/types.js';

	let { theme = 'outline' }: IconProps = $props();

	export const NAME = `IconMinusSmall`;

	const SVGS: Record<IconTheme, string> = {
		outline: `<svg data-type="svelte-heroicons" data-icon="IconMinusSmall" data-theme="outline" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M18 12L6 12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`,
		solid: `<svg data-type="svelte-heroicons" data-icon="IconMinusSmall" data-theme="solid" aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M5.25 12C5.25 11.5858 5.58579 11.25 6 11.25L18 11.25C18.4142 11.25 18.75 11.5858 18.75 12C18.75 12.4142 18.4142 12.75 18 12.75L6 12.75C5.58579 12.75 5.25 12.4142 5.25 12Z" fill="currentColor"/>
</svg>
`,
		mini: `<svg data-type="svelte-heroicons" data-icon="IconMinusSmall" data-theme="mini" aria-hidden="true" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.75 9.25C6.33579 9.25 6 9.58579 6 10C6 10.4142 6.33579 10.75 6.75 10.75L13.25 10.75C13.6642 10.75 14 10.4142 14 10C14 9.58579 13.6642 9.25 13.25 9.25H6.75Z" fill="currentColor"/>
</svg>
`,
		micro: `<!-- Missing Icon -->`
	};
</script>

{@html SVGS[theme]}
